'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { type Report } from '@/lib/types';
import RiskBadge from '@/components/RiskBadge';
import LoadingSpinner from '@/components/LoadingSpinner';
import {
  FileDown,
  Download,
  Trash2,
  Clock,
  FileText,
  AlertTriangle,
  Shield,
} from 'lucide-react';
import styles from './page.module.css';

export default function DownloadsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);

  useEffect(() => {
    fetchReports();
  }, []);

  async function fetchReports() {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const { data } = await supabase
      .from('reports')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false });

    if (data) setReports(data);
    setLoading(false);
  }

  const handleDownload = (report: Report) => {
    const link = document.createElement('a');
    link.href = report.file_url;
    link.download = report.file_name;
    link.target = '_blank';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDelete = async (reportId: string) => {
    if (confirmDeleteId !== reportId) {
      setConfirmDeleteId(reportId);
      return;
    }

    setDeletingId(reportId);
    setConfirmDeleteId(null);

    try {
      const res = await fetch('/api/delete-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reportId }),
      });

      if (!res.ok) {
        throw new Error('Failed to delete report');
      }

      setReports((prev) => prev.filter((r) => r.id !== reportId));
    } catch (err) {
      console.error('Delete error:', err);
      alert('Failed to delete report. Please try again.');
    } finally {
      setDeletingId(null);
    }
  };

  if (loading) {
    return (
      <div className={styles.page}>
        <div className={styles.loadingWrap}>
          <LoadingSpinner text="Loading reports..." />
        </div>
      </div>
    );
  }

  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <div>
          <h1 className={styles.title}>Downloads</h1>
          <p className={styles.subtitle}>
            Your generated evidence reports — download again or manage them here.
          </p>
        </div>
      </div>

      {/* Info banner */}
      <div className={styles.infoBanner}>
        <Shield size={18} className={styles.infoBannerIcon} />
        <p>
          These PDF reports are certified evidence documents generated by ShieldHer&apos;s AI. 
          They can be shared with a <strong>lawyer, counselor, or law enforcement</strong> as supporting evidence.
        </p>
      </div>

      {reports.length > 0 ? (
        <div className={styles.list}>
          {reports.map((report) => (
            <div key={report.id} className={styles.reportCard}>
              <div className={styles.reportMain}>
                <div className={styles.reportIcon}>
                  <FileText size={22} />
                </div>
                <div className={styles.reportInfo}>
                  <div className={styles.reportNameRow}>
                    <span className={styles.reportName}>{report.file_name}</span>
                    <RiskBadge level={report.risk_level} size="sm" />
                  </div>
                  <div className={styles.reportMeta}>
                    <Clock size={12} />
                    <span>
                      {new Date(report.created_at).toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric',
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </span>
                  </div>
                </div>
              </div>

              <div className={styles.reportActions}>
                <button
                  className={styles.downloadBtn}
                  onClick={() => handleDownload(report)}
                  title="Download report"
                >
                  <Download size={16} />
                  Download
                </button>
                <button
                  className={`${styles.deleteBtn} ${confirmDeleteId === report.id ? styles.deleteBtnConfirm : ''}`}
                  onClick={() => handleDelete(report.id)}
                  disabled={deletingId === report.id}
                  title={confirmDeleteId === report.id ? 'Click again to confirm' : 'Delete report'}
                >
                  {deletingId === report.id ? (
                    <>Deleting...</>
                  ) : confirmDeleteId === report.id ? (
                    <>
                      <AlertTriangle size={14} />
                      Confirm Delete
                    </>
                  ) : (
                    <>
                      <Trash2 size={14} />
                      Delete
                    </>
                  )}
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className={styles.empty}>
          <FileDown size={48} />
          <h3>No reports generated yet</h3>
          <p>
            Go to any analysis result and click &quot;Download PDF Report&quot; to generate
            your first evidence document.
          </p>
        </div>
      )}
    </div>
  );
}
